sudo:
  false

language:
  python

python:
  - 2.7

services:
  - docker

install:
  - make develop

script:
  - make build
  - make lint
  - make test

deploy:
  provider: script
  script: make deploy
  on:
    tags: true
