create:
  image: opentrialsrobot/warehouse
  command: python -m warehouse.database.schema
  environment:
    OPENTRIALS_WAREHOUSE_URL:
    OPENTRIALS_DATABASE_URL:

nct:
  image: opentrialsrobot/warehouse
  command: python -m warehouse.database.nct
  environment:
    OPENTRIALS_WAREHOUSE_URL:
    OPENTRIALS_DATABASE_URL:
